// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ModelitzarUML.vendes.vendes;

import ModelitzarUML.vendes.vendes.Cliente;
import java.lang.String;

/************************************************************/
/**
 * 
 */
public class ClienteCorporativo extends Cliente {
	/**
	 * 
	 */
	private String idCliCorp;

	/**
	 * 
	 * @return 
	 */
	public String getIdCliCorp() {

		return idCliCorp;
	}

	/**
	 * 
	 * @param idCliCorp 
	 */
	public void setIdCliCorp(String idCliCorp) {

		this.idCliCorp = idCliCorp;
	}
};
