// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ModelitzarUML.vendes.vendes;

import ModelitzarUML.vendes.vendes.Cliente;
import java.lang.String;

/************************************************************/
/**
 * 
 */
public class ClientePersonal extends Cliente {
	/**
	 * 
	 */
	private String idcliPer;

	/**
	 * 
	 * @return 
	 */
	public String getIdcliPer() {

		return idcliPer;
	}

	/**
	 * 
	 * @param idcliPer 
	 */
	public void setIdcliPer(String idcliPer) {

		this.idcliPer = idcliPer;
	}
};
