// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ModelitzarUML.vendes.vendes;

import ModelitzarUML.vendes.vendes.SistemaPago;
import java.lang.String;

/************************************************************/
/**
 * 
 */
public class Contrato extends SistemaPago {
	/**
	 * 
	 */
	private int lineaCredito;
	/**
	 * 
	 */
	private String nom;
	/**
	 * 
	 */
	private String cognoms;
	/**
	 * 
	 */
	private String idPersona;

	/**
	 * 
	 * @return 
	 */
	public int getLineaCredito() {

		return lineaCredito;
	}

	/**
	 * 
	 * @param lineaCredito 
	 */
	public void setLineaCredito(int lineaCredito) {

		this.lineaCredito = lineaCredito;
	}

	/**
	 * 
	 * @return 
	 */
	public String getNom() {

		return nom;
	}

	/**
	 * 
	 * @param nom 
	 */
	public void setNom(String nom) {

		this.nom = nom;
	}

	/**
	 * 
	 * @return 
	 */
	public String getCognoms() {

		return cognoms;
	}

	/**
	 * 
	 * @param cognoms 
	 */
	public void setCognoms(String cognoms) {

		this.cognoms = cognoms;
	}

	/**
	 * 
	 * @return 
	 */
	public String getIdPersona() {

		return idPersona;
	}

	/**
	 * 
	 * @param idPersona 
	 */
	public void setIdPersona(String idPersona) {

		this.idPersona = idPersona;
	}
};
