// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ModelitzarUML.vendes.vendes;

import ModelitzarUML.vendes.vendes.Producto;

/************************************************************/
/**
 * 
 */
public class LiniaPedido {
	/**
	 * 
	 */
	private int idLiniaPedido;
	/**
	 * 
	 */
	private float preu;
	/**
	 * 
	 */
	private Producto[] Llista;

	/**
	 * 
	 * @return 
	 */
	public int getIdLiniaPedido() {

		return idLiniaPedido;
	}

	/**
	 * 
	 * @param idLiniaPedido 
	 */
	public void setIdLiniaPedido(int idLiniaPedido) {

		this.idLiniaPedido = idLiniaPedido;
	}

	/**
	 * 
	 * @return 
	 */
	public float getPreu() {

		return preu;
	}

	/**
	 * 
	 * @param preu 
	 */
	public void setPreu(float preu) {

		this.preu = preu;
	}

	/**
	 * 
	 * @return 
	 */
	public Producto[] getLlista() {

		return Llista;
	}

	/**
	 * 
	 * @param llista 
	 */
	public void setLlista(Producto[] llista) {

		Llista = llista;
	}
};
