// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ModelitzarUML.vendes.vendes;

import ModelitzarUML.vendes.vendes.LiniaPedido;

/************************************************************/
/**
 * 
 */
public class Pedidos {
	/**
	 * 
	 */
	private LiniaPedido liniaPedido;
	/**
	 * 
	 */
	private int idPedido;

	/**
	 * 
	 * @return 
	 */
	public LiniaPedido getLiniaPedido() {

		return liniaPedido;
	}

	/**
	 * 
	 * @param liniaPedido 
	 */
	public void setLiniaPedido(LiniaPedido liniaPedido) {

		this.liniaPedido = liniaPedido;
	}

	/**
	 * 
	 * @return 
	 */
	public int getIdPedido() {

		return idPedido;
	}

	/**
	 * 
	 * @param idPedido 
	 */
	public void setIdPedido(int idPedido) {

		this.idPedido = idPedido;
	}
};
