// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ModelitzarUML.vendes.vendes;

import java.lang.String;

/************************************************************/
/**
 * 
 */
public class Producto {
	/**
	 * 
	 */
	private int idProducte;
	/**
	 * 
	 */
	private String nom;
	/**
	 * 
	 */
	private float preu;

	/**
	 * 
	 * @return 
	 */
	public int getIdProducte() {

		return idProducte;
	}

	/**
	 * 
	 * @param idProducte 
	 */
	public void setIdProducte(int idProducte) {

		this.idProducte = idProducte;
	}

	/**
	 * 
	 * @return 
	 */
	public String getNom() {

		return nom;
	}

	/**
	 * 
	 * @param nom 
	 */
	public void setNom(String nom) {

		this.nom = nom;
	}

	/**
	 * 
	 * @return 
	 */
	public float getPreu() {

		return preu;
	}

	/**
	 * 
	 * @param preu 
	 */
	public void setPreu(float preu) {

		this.preu = preu;
	}
};
