// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ModelitzarUML.vendes.vendes;

import java.lang.String;

/************************************************************/
/**
 * 
 */
public class SistemaPago {
	/**
	 * 
	 */
	public String pedido;
	/**
	 * 
	 */
	public float preu;

	/**
	 * 
	 * @return 
	 */
	public float consultarSaldo() {

		return 2.3f;
	}
};
