// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ModelitzarUML.vendes.vendes;

import ModelitzarUML.vendes.vendes.SistemaPago;
import java.lang.String;

/************************************************************/
/**
 * 
 */
public class TarjetaCredito extends SistemaPago {
	/**
	 * 
	 */
	private String idUsuari;
	/**
	 * 
	 */
	private String nom;
	/**
	 * 
	 */
	private String cognoms;
	/**
	 * 
	 */
	private float saldo;

	/**
	 * 
	 * @return 
	 */
	public String getIdUsuari() {

		return idUsuari;
	}

	/**
	 * 
	 * @param idUsuari 
	 */
	public void setIdUsuari(String idUsuari) {

		this.idUsuari = idUsuari;
	}

	/**
	 * 
	 * @return 
	 */
	public String getNom() {

		return nom;
	}

	/**
	 * 
	 * @param nom 
	 */
	public void setNom(String nom) {

		this.nom = nom;
	}

	/**
	 * 
	 * @return 
	 */
	public String getCognoms() {

		return cognoms;
	}

	/**
	 * 
	 * @param cognoms 
	 */
	public void setCognoms(String cognoms) {

		this.cognoms = cognoms;
	}

	/**
	 * 
	 * @return 
	 */
	public float getSaldo() {

		return saldo;
	}

	/**
	 * 
	 * @param saldo 
	 */
	public void setSaldo(float saldo) {

		this.saldo = saldo;
	}

	/**
	 * 
	 * @param saldo 
	 */
	public void pagar(float saldo) {

	}

	/**
	 * 
	 * @param saldo 
	 */
	public void ingressar(float saldo) {

	}
};
