// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ModelitzarUML.vendes.vendes;

import java.lang.String;

/************************************************************/
/**
 * 
 */
public class Vendedor {
	/**
	 * 
	 */
	private String nom;
	/**
	 * 
	 */
	private String cognoms;
	/**
	 * 
	 */
	private String idVenedor;

	/**
	 * 
	 * @return 
	 */
	public String getNom() {

		return nom;
	}

	/**
	 * 
	 * @param nom 
	 */
	public void setNom(String nom) {

		this.nom = nom;
	}

	/**
	 * 
	 * @return 
	 */
	public String getCognoms() {

		return cognoms;
	}

	/**
	 * 
	 * @param cognoms 
	 */
	public void setCognoms(String cognoms) {

		this.cognoms = cognoms;
	}

	/**
	 * 
	 * @return 
	 */
	public String getIdVenedor() {

		return idVenedor;
	}

	/**
	 * 
	 * @param idVenedor 
	 */
	public void setIdVenedor(String idVenedor) {

		this.idVenedor = idVenedor;
	}
};
