// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ModelitzarUML;

/************************************************************/
/**
 * 
 */
public class ClientePersonal extends Cliente {
	/**
	 * 
	 */
	private int idCPersonal;
};
