// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ModelitzarUML;

/************************************************************/
/**
 * 
 */
public class ClienteCorporativo extends Cliente {
	/**
	 * 
	 */
	private int idCCorporatiu;
};
