// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ModelitzarUML;

/************************************************************/
/**
 * 
 */
public class Cliente {
	/**
	 * 
	 */
	private String nom;
	/**
	 * 
	 */
	public int idClient;
	/**
	 * 
	 */
	public Pedido[] comandes;
};
