// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ModelitzarUML;

/************************************************************/
/**
 * 
 */
public class LineaPedido {
	/**
	 * 
	 */
	private Producto[] productes;
	/**
	 * 
	 */
	private int codi;
};
