// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ModelitzarUML;

/************************************************************/
/**
 * 
 */
public class Pedido {
	/**
	 * 
	 */
	private int idPedido;
	/**
	 * 
	 */
	private Producto[] productes;
};
