// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ModelitzarUML;

/************************************************************/
/**
 * 
 */
public class Producto {
	/**
	 * 
	 */
	private int idProducte;
	/**
	 * 
	 */
	private String nom;
	/**
	 * 
	 */
	public float preu;

	/**
	 * 
	 */
	public void getidProducte() {
	}
};
