// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ModelitzarUML;

/************************************************************/
/**
 * 
 */
public class SistemaDePago {
	/**
	 * 
	 */
	private int consultarSaldo;
};
