// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ModelitzarUML;

import ModelitzarUML.SistemaDePago;

/************************************************************/
/**
 * 
 */
public class TargetaCredito extends SistemaDePago {
	/**
	 * 
	 */
	private int lineaCredito;
};
