// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ModelitzarUML;

import ModelitzarUML.SistemaDePago;

/************************************************************/
/**
 * 
 */
public class Vendedor {
	/**
	 * 
	 */
	private int idVenedor;
	/**
	 * 
	 */
	private String nom;
	/**
	 * 
	 */
	private int vendes;
};
